version: "3"
services:
    web:
        image: trafex/php-nginx
        ports:
            - 80:8080
        volumes:
            - .:/var/www/html
    db:
        image: mariadb
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ocapstats
            MYSQL_ROOT_PASSWORD: rootpass
        volumes:
            - mysqldata:/var/lib/mysql
            - ./.sql/db.skeleton.sql:/docker-entrypoint-initdb.d/ocap-stats.skeleton.sql:ro
    adminer:
        image: adminer
        ports:
            - 8080:8080
volumes:
    mysqldata: {}
